examiner/urls.py
from django.conf.urls import url

from examiner import views


urlpatterns = [
    url(
        r'^$',
        views.SearchView.as_view(),
        name='search',
    ),
    url(
        r'^verify$',
        views.VerifyView.as_view(),
        name='verify_random',
    ),
    url(
        r'^verify/(?P<sha1_hash>[0-9a-f]{40})$',
        views.VerifyView.as_view(),
        name='verify_pdf',
    ),
    url(
        r'^course/$',
        views.ExamsView.as_view(),
        name='all_exams',
    ),
    url(
        r'^course/(?P<course_code>.+)$',
        views.ExamsView.as_view(),
        name='course',
    ),
    url(
        r'^course-autocomplete/$',
        views.CourseWithExamsAutocomplete.as_view(),
        name='course_autocomplete',
    ),
]

kokekunster/urls.py
import os

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'^accounts/', include('allauth.urls')),
    url(r'^exams/', include('examiner.urls', namespace='examiner')),
    url(
        r'^api/exams/',
        include('examiner.urls', namespace='examiner'),
        {'api': True},
    ),
    url(r'^', include('semesterpage.urls')),
]

if not os.environ.get('PRODUCTION', False):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

examiner/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Fieldset, Layout, Submit

from dal import autocomplete

from examiner.models import DocumentInfoSource, DocumentInfo, Pdf
from semesterpage.models import Course


class VerifyExamForm(forms.ModelForm):
    courses = forms.ModelMultipleChoiceField(
        label=_('Fag'),
        queryset=Course.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(
            url='semesterpage-course-autocomplete',
            attrs={
                'data-placeholder': _('Fagkode/fagnavn'),

                # Only trigger autocompletion after 3 characters have been typed
                'data-minimum-input-length': 3,
            },
        )
    )
    pdf = forms.ModelChoiceField(
        label=_('Pdf'),
        queryset=Pdf.objects.all(),
    )
    verifier = forms.ModelChoiceField(
        label=_('Bruker som verifiserer'),
        queryset=get_user_model().objects.all(),
    )

    class Meta:
        model = DocumentInfo
        exclude = ['course', 'course_code']
        labels = {
            'language': _('Språk'),
            'year': _('År'),
            'season': _('Semestertype'),
            'content_type': _('Dokumenttype'),
            'solutions': _('LF'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'verify-form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('examiner:verify_random')

        self.helper.layout = Layout(
            Fieldset(
                _('PDF klassifisering'),
                Field(
                    'content_type',
                    onchange='onContentTypeChange()',
                ),
                'courses',
                'language',
                'year',
                'season',
                'solutions',
                'exercise_number',
                Field('pdf', type='hidden', readonly=True),
                Field('verifier', type='hidden', readonly=True),
            ),
            Submit(
                'verify',
                _('&check; Verifiser'),
                css_class='btn btn-success btn-block',
            ),
            # Submit(
            #     'trash',
            #     _('✖ Slett'),
            #     css_class='btn btn-danger btn-block',
            # ),
        )

        # Change semester type radio button labels
        self.fields['season'].choices = [
            (1, 'Vår'),
            (2, 'Kont'),
            (3, 'Høst'),
            (None, 'Ukjent'),
        ]

        # Set required fields
        self.fields['pdf'].required = True
        self.fields['verifier'].required = True

    def save(self, commit=True):
        # Only committing save is implemented ATM
        assert commit

        docinfo = self.instance
        data = self.cleaned_data

        # Save to self in order to use this in VerifyView.form_valid
        self.courses = data.pop('courses')

        pdf = data.pop('pdf')
        verifier = data.pop('verifier')

        for course in self.courses:
            docinfo, _ = DocumentInfo.objects.get_or_create(
                course=course,
                course_code=course.course_code,
                **data,
            )
            exam_pdf, _ = DocumentInfoSource.objects.get_or_create(
                document_info=docinfo,
                pdf=pdf,
            )
            exam_pdf.verified_by.add(verifier)
            exam_pdf.save()

        # Remove all unverified document infos for this PDF
        DocumentInfoSource.objects.filter(
            pdf=pdf,
            verified_by__isnull=True,
        ).delete()


class ExamsSearchForm(forms.Form):
    """Form used for searching for exam archive for specific course."""

    # Using ModelMultipleChoiceField here even though only one course is
    # intendede to be submitted at a time. The multiple choice styling looks
    # better in the frontend.
    course = forms.ModelMultipleChoiceField(
        label=_('Fag'),
        queryset=Course.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(
            url='examiner:course_autocomplete',
            attrs={
                'data-placeholder': _('Fagkode/fagnavn'),

                # Only trigger autocompletion after 1 character has been typed
                'data-minimum-input-length': 1,
            },
        )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'search-form'
        self.helper.form_method = 'post'

        # Post to same page
        self.helper.form_action = ''

        # Hide field labels
        self.helper.form_show_labels = False

        self.helper.layout = Layout(
            Fieldset(
                _('Tast inn fag'),
                Field(
                    'course',
                    onchange='search();',
                    css_class='form-control-lg',
                ),
            ),
        )

examiner/views.py
from random import randint

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import F
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from examiner.forms import ExamsSearchForm, VerifyExamForm
from examiner.models import DocumentInfo, DocumentInfoSource, Pdf, PdfUrl
from semesterpage.models import Course, Semester, StudyProgram
from semesterpage.views import CourseAutocomplete


DEFAULT_SEMESTER_PK = getattr(settings, 'DEFAULT_SEMESTER_PK', 1)


class ExamsView(ListView):
    model = PdfUrl
    template_name = 'examiner/exam_archive.html'
    http_method_names = ['get']

    def get_context_data(self, **kwargs):
        super().get_context_data(**kwargs)
        course_code = self.kwargs.get('course_code')
        docinfos = (
            DocumentInfo
            .objects
            .order_by(
                F('course_code'),
                F('year').desc(nulls_last=True),
                F('solutions').desc(),
            )
        )
        if course_code:
            docinfos = docinfos.filter(
                course_code__iexact=course_code.upper(),
            )

        context = {'exam_courses': docinfos.organize()}

        if self.kwargs.get('api'):
            # Early return if this is the API view
            return context['exam_courses']

        add_context(request=self.request, context=context)
        if course_code:
            context['header_text'] = f' / exams / ' + course_code
            context['course'] = Course.objects.get(
                course_code=course_code.upper(),
            )
        else:
            context['header_text'] = ' / exams'

        return context

    def get(self, request, *args, **kwargs):
        if self.kwargs.get('api'):
            # Hacky override for API version of this view
            self.object_list = self.get_queryset()
            organization = self.get_context_data()
            return JsonResponse(organization)

        # Normal template response
        return super().get(request, *args, **kwargs)


class VerifyView(LoginRequiredMixin, FormView):
    template_name = 'examiner/verify.html'
    form_class = VerifyExamForm
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        """View for verifying PDF exam information."""
        sha1_hash = self.kwargs.get('sha1_hash')
        if sha1_hash:
            pdf = get_object_or_404(
                klass=Pdf,
                sha1_hash=sha1_hash,
            )
        else:
            exam_pdfs = DocumentInfoSource.objects.filter(
                verified_by__isnull=True,
            )
            pdf = exam_pdfs[randint(0, exam_pdfs.count() - 1)].pdf

        exams = pdf.exams.all()
        form = VerifyExamForm(
            instance=pdf.exams.first(),
            initial={
                'courses': exams.values_list('course', flat=True),
                'pdf': pdf,
                'verifier': request.user,
            },
        )
        context = {'pdf': pdf, 'form': form}
        add_context(request, context)
        return render(request, 'examiner/verify.html', context)

    @transaction.atomic
    def form_valid(self, form):
        form.save(commit=True)
        courses = form.courses
        if courses.exists():
            # Redirect to first course exam archive view
            course_code = courses.first().course_code
            return redirect(to='examiner:course', course_code=course_code)
        return redirect(to='examiner:verify_random')


class CourseWithExamsAutocomplete(CourseAutocomplete):
    """Autocompletion view for courses with related exams."""

    LOGIN_REQUIRED = False

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(docinfos__isnull=False).distinct()


class SearchView(FormView):
    """View for course search."""

    template_name = 'examiner/search.html'
    form_class = ExamsSearchForm
    http_method_names = ['get', 'post']

    def form_valid(self, form):
        """Redirect to exam archive for course."""
        # Get the first element, because we use a multiple choice field for
        # aesthetic reasons.
        course = form.cleaned_data['course'][0]
        return redirect(
            to='examiner:course',
            course_code=course.course_code,
        )

    def get_context_data(self, **kwargs):
        """Add navigation bar content."""
        context = super().get_context_data(**kwargs)
        add_context(request=self.request, context=context)
        context['exam_count'] = Pdf.objects.count()
        context['course_count'] = (
            DocumentInfoSource
            .objects.distinct('document_info__course_code')
            .count()
        )
        return context


def add_context(request, context):
    """Add context required for navbar rendering."""
    semester_pk = request.session.get('semester_pk', DEFAULT_SEMESTER_PK)
    try:
        semester = Semester.objects.get(pk=semester_pk)
    except Semester.DoesNotExist:
        semester = None

    new_context = {
        'user': request.user,
        'study_programs': StudyProgram.objects.filter(published=True),
        'semester': semester,
    }
    context.update(new_context)

examiner/templates/examiner/exam_archive.html
{% extends "base.html" %} {# TODO: Need to add link category and course static images based on model #}
{% load rules static %}

{% block navbar %}
{% include "semesterpage/navbar.html" %}
{% endblock %}

{% block content %}


<!-- For table styling -->
<link
  rel="stylesheet"
  href="https://unpkg.com/purecss@1.0.0/build/pure-min.css"
  integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w"
  crossorigin="anonymous">

<!-- Required for search functionality -->
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<!-- Required for tooltip on hover -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>

<script src="{% static 'js/jquery.searchable-1.1.0.min.js' %}"></script>

<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
  integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
  crossorigin="anonymous">

{% for course_code, course_content in exam_courses.items %}
<div class="course container-fluid" style="overflow-x: auto;">
<div class="row"> {# all the content is in one row #}
<div class="col"></div> {# empty left column #}

<div class="col-7"> {# center content #}
<h1 class="mx-auto text-center mt-5" style="font-size: 3em;">
  {{ course_code }}
  {% if course_content.nick_name %}
  <br>
  {{ course_content.nick_name }}
  {% elif course_content.full_name %}
  <br>
  {{ course_content.full_name }}
  {% endif %}
</h1>

<div class="text-center mt-3">
  <a href="{% url "examiner:search" %}">
    <button
      type="button"
      class="mx-auto btn btn-outline-secondary btn-lg"
      style="width: 10em;">
      <i class="fa fa-search"></i>
      Nytt fagsøk
    </button>
  </a>
  <button
    type="button"
    class="mx-auto btn btn-outline-secondary btn-lg"
    data-toggle="collapse"
    data-target=".fix-button"
    style="width: 10em;">
    <i class="fa fa-pencil"></i>
    Fiks feil
  </button>
</div>

<div class="input-group input-group-lg my-3">
  <input type="text" class="form-control class-search mx-auto" id="search-{{ course_code }}" placeholder="Søk i eksamstekst"></input>
</div>

<table id="table-{{ course_code }}" class="pure-table mx-auto mb-5">
  <tr>
    <th>År</th>
    <th>Semester</th>
    <th>Eksamen</th>
    <th>LF</th>
  </tr>

  {% for year, seasons in course_content.years.items %}
  {% for season, exam_set in seasons.items %}
  <tr>
    <td>{{ year|default:"Ukjent" }}</td>

    <td>
      {% if season == 'Høst' %}
      Høst
      {% elif season == 'Vår' %}
      Vår
      {% elif season == 'Kont' %}
      Kont
      {% else %}
      Ukjent
      {% endif %}
    </td>

    <td>
      {# Iterate over all the exam languages #}
      {% for language, pdfs in exam_set.exams.items %}
      {% include 'examiner/pdf_links.html' %}
      {% endfor %}
    </td>

    <td>
      {# Iterate over all the solution languages #}
      {% for language, pdfs in exam_set.solutions.items %}
      {% include 'examiner/pdf_links.html' %}
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
  {% endfor %}
</table>
{% endfor %}

</div> {# center table column #}

<div class="col" style="padding-top: 19.3em;">
  <div class="card w-75 d-none d-xl-block mx-auto" id="course-card">
    <div class="card-body">
      <div class="content" style="display: block;">
        {% include "semesterpage/course.html" %}
      </div> {# content #}
    </div> {# card-body #}
  </div> {# card #}
</div> {# right column #}

</div> {# row #}
{% endblock %}

{% block end %}
{# Prevent usage of bootstrap as it breaks PureCSS tables #}
<script src="{% static 'examiner/js/collapse.js' %}"></script>

<script>
$(document).tooltip({
  show: {
    delay: 0,
    duration: 0,
  },
  hide: {
    delay: 0,
    duration: 0,
  },
})


$( 'table' ).each(function() {
  var currentTable = $(this);
  var currentTableID = currentTable.attr('id');
  var currentSearchInputID = currentTableID.replace('table', 'search');
  currentTable.searchable({
    searchField: '#' + currentSearchInputID,
    clearOnLoad: true,
    selector: 'tbody tr:nth-child(n+2)',
    striped: true,
    oddRow: {'background-color': '#efefef'},
    evenRow: {'background-color': 'white'}
  });
});
</script>

<style>
table {
  width: 100%;
}
thead tr th:nth-child(-n + 2),
tbody tr td:nth-child(-n + 2) {
  width: 5em;
  max-width: 5em;
}
thead tr th:nth-child(n + 3),
tbody tr td:nth-child(n + 3) {
  padding-right: 5em;
}
tr {
  vertical-align: baseline;
}
th {
  text-align: left;
}
tr:nth-child(1) {
  background-color: #7a7a7a;
  color: white;
}

/* Overwrite bootstrap which changes anchor tags styling */
tr a:not(.btn) {
  text-decoration: none;
  color: black;
  cursor: pointer;
}
tr a:visited:not(.btn) {
  color: black;
}
.card a {
  color: black;
}

/* Mutate margins in order to look nice within a BS4 card */
div .content {
  margin-top: -0.7em;
  margin-left: 1em;
  margin-bottom: -1.5em;
}

.mainLanguageLink:hover {
  color: white;
  background: #7a7a7a;
}
</style>
{% endblock %}

examiner/templates/examiner/pdf_links.html
{# Iterate over all the PDFs available for the category #}
{# Requires context variables: pdfs, language #}
{% for sha1, pdf in pdfs.items %}

{# First the main PDF for the category #}
{% if forloop.first %}

{# Add hidden fix button #}
<a
  type="button"
  class="btn btn-outline-success btn-sm mr-2 fix-button collapse multi-collapse"
  href="{% url 'examiner:verify_pdf' sha1 %}">
  Fiks
</a>

{# Link to the first PDF with filename #}
<a href="{{ pdf.backup_url }}" target="_blank" style="display: inline-block; height: 100%; min-width: 20rem;" class="mainLanguageLink">
  <div class="my-1 mainLanguageLink mr-2" style="display: inline-block;">
    {% if language == 'Engelsk' %}
    🇬🇧
    {% elif language == 'Nynorsk' %}
    🇳🇴
    {% elif language == 'Bokmål' %}
    🇳🇴
    {% else %}
    &nbsp;<i class="fa fa-question-circle" style="color:grey"></i>
    {% endif %}
    <i>{{ pdf.filename | truncatechars:25 }}</i>
    {% if language == 'Nynorsk' %}
    <div style="color: silver; display: inline-block;">(nynorsk)</div>
    {% endif %}
  </div>
</a>

{# Add we now add all the alternative PDFs with counters #}
{% elif forloop.counter > 1 %}

{# Open secondary link div #}
{% if forloop.counter == 2 %}
<div style="display: inline-block;">
  <i class="fa fa-external-link"></i>
{% endif %}

  <a href="{{ pdf.backup_url }}" title="{{ pdf.filename }}" target="_blank" class="badge badge-secondary" style="color: white; vertical-align: text-top;">
      {{ forloop.counter }}
  </a>

{# Close secondary link div #}
{% if forloop.last %}
</div>
{% endif %}

{% endif %}

{# Add hidden text field for this PDF, used for searching #}
<div style="display:none;">{{ pdf.text }}</div>

{% endfor %}

{# Break between languages #}
<br>

examiner/templates/examiner/search.html
{% extends "base.html" %}
{% load rules static %}
{% load crispy_forms_tags %}

{% block extra_css %}
{# Stuff for bootstrap v4 used in django-crispy-forms #}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

{# For django-autocomplete-light #}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{% endblock %}

{% block navbar %}
{% include "semesterpage/navbar.html" %}
{% endblock %}


{% block content %}
<div class="container text-center pt-5" id="search-content">
  <img src="{% static "examiner/img/examiner_logo.svg" %}" alt="eksamensarkiv">
  <h1 class="my-2" style="font-size: 3em; font-weight: bold;">
    Eksamensarkiv
  </h1>
  <h4 id="exam-count" style="color: grey;">
    <i>
        {{ exam_count }} PDFer, {{ course_count }} fag
    </i>
  </h4>

  <div class="my-5">
    {% crispy form %}
  </div>
</div>
{% endblock %}

{% block end %}

<style>
legend {
  display: none;
}

.selection {
  font-size: 2.5em;
}

{% include 'examiner/loader.css' %}
</style>

<script>
function search() {
  /* Submit the search form for redirection */
  form = document.getElementById("search-form");
  form.submit();

  /* Insert loading navigation */
  content = document.getElementById("search-content");
  content.innerHTML = '\
    <div class="cssload-thecube" style="margin-bottom: 100px; margin-top: 100px;">\
      <div class="cssload-cube cssload-c1"></div>\
      <div class="cssload-cube cssload-c2"></div>\
      <div class="cssload-cube cssload-c4"></div>\
      <div class="cssload-cube cssload-c3"></div>\
    </div>';

}

/* Force page reload when user hits back button */
/* Prevents eternal reload screen */
/* Taken from: https://codepen.io/derekjp/pen/Bguwz */
$(window).bind("pageshow", function(event) {
    if (event.originalEvent.persisted) {
        window.location.reload();
    }
});

/* Select search input on site load */
$(document).ready(function() {$(".select2-search__field")[0].focus()})
</script>

{% endblock %}

examiner/templates/examiner/verify.html
{% extends "base.html" %}
{% load rules static %}
{% load crispy_forms_tags %}

{% block extra_css %}
{# Stuff for bootstrap v4 used in django-crispy-forms #}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

{# For django-autocomplete-light #}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{# For hiding exercise number for irrelevant content types #}
<script type="text/javascript">
  function onContentTypeChange() {
    select = document.getElementById('id_content_type');
    newValue = select.options[select.selectedIndex].value;
    exerciseField = document.getElementById('div_id_exercise_number');
    console.log(exerciseField);

    if (newValue === 'Exercise' || newValue === 'Project') {
      exerciseField.style.display = 'block';
    } else {
      exerciseField.style.display = 'none';
    }
  }
</script>
{% endblock %}

{% block navbar %}
{% include "semesterpage/navbar.html" %}
{% endblock %}

{% block content %}

<div class="container mt-3">
<div class="row">


<div class="col">
<div id="pdf">
    <object
      id="pdf_content"
      width="100%"
      height="1075px"
      type="application/pdf"
      trusted="yes"
      application="yes"
      title="Assembly"
      data="{{ pdf.file.url }}?#zoom=100&scrollbar=1&toolbar=1&navpanes=1">
    <p>Kan ikke laste inn PDF, prøv med Mozilla Firefox.</p>
    </object>
</div>
</div>

<div class="col-3">
{% crispy form %}

<div class="card bg-light mt-4">
  <div class="card-body">
    <h5 class="card-title">URLer</h5>
    <h6 class="card-subtitle mb-2 text-muted">
      Hvor PDFen kan lastes ned.
    </h6>
  </div>
  <ul class="list-group list-group-flush">
    {% for url in pdf.hosted_at.all %}
    <li class="list-group-item">
      <a href="{{ url.url }}"> {{ url.filename }} </a>
    </li>
    {% endfor %}
  </ul>
</div>


</div>
</div>
</div>

{% endblock %}

{% block end %}
<script type="text/javascript">
  window.onload = onContentTypeChange;
</script>
{% endblock %}